services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=ITproject76!'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=ricouser'
    ports:
      - '3306'